/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppTest.codes;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DBeatz
 */
public class AppTest extends javax.swing.JFrame {

    /**
     * Creates new form AppTest
     */
    public AppTest() {
        initComponents();
    }
    
    public void OpenWeb(){
        try {
            String search = SearchText.getText().toString();
            String url ="www.google.com/#q="+search;
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
            Logger.getLogger(AppTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseBut = new javax.swing.JLabel();
        SearchBut = new javax.swing.JLabel();
        SearchText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Backgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(630, 500));
        setMinimumSize(new java.awt.Dimension(630, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(630, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButMouseClicked(evt);
            }
        });
        getContentPane().add(CloseBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 20));

        SearchBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButMouseClicked(evt);
            }
        });
        getContentPane().add(SearchBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 110, 40));

        SearchText.setBackground(new java.awt.Color(157, 195, 230));
        SearchText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SearchText.setForeground(new java.awt.Color(255, 255, 255));
        SearchText.setBorder(null);
        SearchText.setOpaque(false);
        getContentPane().add(SearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 450, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(157, 195, 230));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 470, 360));

        Backgrnd.setBackground(new java.awt.Color(157, 195, 230));
        Backgrnd.setForeground(new java.awt.Color(204, 204, 255));
        Backgrnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppTest/images/apptest.png"))); // NOI18N
        getContentPane().add(Backgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 500));

        setSize(new java.awt.Dimension(624, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseButMouseClicked

    private void SearchButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButMouseClicked
        // TODO add your handling code here:
        OpenWeb();
        
    }//GEN-LAST:event_SearchButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgrnd;
    private javax.swing.JLabel CloseBut;
    private javax.swing.JLabel SearchBut;
    private javax.swing.JTextField SearchText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
